In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd  


def simple_linear_svm():
    #download data set: https://drive.google.com/file/d/13nw-uRXPY8XIZQxKRNZ3yYlho-CYm_Qt/view
    #info: https://archive.ics.uci.edu/ml/datasets/banknote+authentication

    # load data
    bankdata = pd.read_csv("./bill_authentication.csv")  

    # see the data
    bankdata.shape  

    # see head
    bankdata.head()  

    # data processing
    X = bankdata.drop('Class', axis=1)  
    y = bankdata['Class']  

    from sklearn.model_selection import train_test_split  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  

    # train the SVM
    from sklearn.svm import SVC  
    svclassifier = SVC(kernel='linear')  
    svclassifier.fit(X_train, y_train)  

    # predictions
    y_pred = svclassifier.predict(X_test)  

    # Evaluate model
    from sklearn.metrics import classification_report, confusion_matrix  
    print(confusion_matrix(y_test,y_pred))  
    print(classification_report(y_test,y_pred))  
    # TODO: Evaluates perfomance of Polynomial Kernel, Gaussian Kernel, and Sigmoid Kernel.
    

In [20]:
# Iris dataset  https://archive.ics.uci.edu/ml/datasets/iris4
def import_iris():
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

    # Assign colum names to the dataset
    colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

    # Read dataset to pandas dataframe
    irisdata = pd.read_csv(url, names=colnames) 

    # process
    X = irisdata.drop('Class', axis=1)  
    y = irisdata['Class']  

    # train
    from sklearn.model_selection import train_test_split  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  
    return (X_train, X_test, y_train, y_test)


In [21]:
def plot_predictions(clf, axes):
    x0s = np.linspace(axes[0], axes[1], 100)
    x1s = np.linspace(axes[2], axes[3], 100)
    x0, x1 = np.meshgrid(x0s, x1s)
    X = np.c_[x0.ravel(), x1.ravel()]
    y_pred = clf.predict(X).reshape(x0.shape)
    y_decision = clf.decision_function(X).reshape(x0.shape)
    plt.contourf(x0, x1, y_pred, cmap=plt.cm.brg, alpha=0.2)
    plt.contourf(x0, x1, y_decision, cmap=plt.cm.brg, alpha=0.1)

In [22]:
def polynomial_kernel():
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.svm import SVC
    from sklearn.metrics import classification_report, confusion_matrix  
    
    X_train, X_test, y_train, y_test = import_iris()
    
    poly_kernel_svm_clf = Pipeline([
        ("scaler", StandardScaler()),
        ("svm_clf", SVC(kernel="poly", degree=8))
    ])

    poly_kernel_svm_clf.fit(X_train, y_train)
    y_pred = poly_kernel_svm_clf.predict(X_test)
    
    print(confusion_matrix(y_test, y_pred))  
    print(classification_report(y_test, y_pred))

In [23]:
def gaussian_kernel():
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.svm import SVC
    from sklearn.metrics import classification_report, confusion_matrix  

    X_train, X_test, y_train, y_test = import_iris()
    
    rbf_svm_clf = Pipeline([
        ("scaler", StandardScaler()),
        ("svm_clf", SVC(kernel="rbf", random_state=42))
    ])

    rbf_svm_clf.fit(X_train, y_train)
    y_pred = rbf_svm_clf.predict(X_test)
    
    print(confusion_matrix(y_test, y_pred))  
    print(classification_report(y_test,y_pred))

In [24]:
def sigmoid_kernel():
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    from sklearn.svm import SVC
    from sklearn.metrics import classification_report, confusion_matrix  
    
    X_train, X_test, y_train, y_test = import_iris()
    
    sigmoid_svm_clf = Pipeline([
        ("scaler", StandardScaler()),
        ("svm_clf", SVC(kernel="sigmoid", random_state=42))
    ])

    sigmoid_svm_clf.fit(X_train, y_train)
    y_pred = sigmoid_svm_clf.predict(X_test)
    
    print(confusion_matrix(y_test, y_pred))  
    print(classification_report(y_test,y_pred))

### Polynomial Kernel Results

In [25]:
polynomial_kernel()

[[ 4  1  1]
 [ 0 12  0]
 [ 1  5  6]]
                 precision    recall  f1-score   support

    Iris-setosa       0.80      0.67      0.73         6
Iris-versicolor       0.67      1.00      0.80        12
 Iris-virginica       0.86      0.50      0.63        12

      micro avg       0.73      0.73      0.73        30
      macro avg       0.77      0.72      0.72        30
   weighted avg       0.77      0.73      0.72        30



### Gaussian Kernel Results

In [26]:
gaussian_kernel()

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

      micro avg       1.00      1.00      1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



### Results Sigmoid Kernel

In [27]:
sigmoid_kernel()

[[8 0 0]
 [0 8 5]
 [0 3 6]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       0.73      0.62      0.67        13
 Iris-virginica       0.55      0.67      0.60         9

      micro avg       0.73      0.73      0.73        30
      macro avg       0.76      0.76      0.76        30
   weighted avg       0.75      0.73      0.74        30

